# Display ascii art 
print("##########")
print(" O       O")
print("     0    ")
print("##########")
print("##########>>>>>>>>>>")
print("##########>>>>>>>>>>")
print("@@@@@O@@@@")
print("@@@@@@@@@@")
print("x         x")
print("x         x")
print("x         x")
print("x         x")
print("MMMM      MMMM")
